title: The Fuzzing Book
author: Andreas Zeller, Rahul Gopinath, Marcel Böhme, Gordon Fraser, and Christian Holler
copyright: 2021-2025 CISPA Helmholtz Center for Information Security (www.cispa.de); Copyright &copy; 2018-2020 Saarland University, authors, and contributors. All Rights Reserved
# exclude_patterns: [BookIntro.md]

bibtex_bibfiles:
  - fuzzingbook.bib

latex:
  latex_documents:
     targetname: fuzzingbook.tex

sphinx:
  config:
    latex_engine: xelatex
    latex_show_pagerefs: true
    latex_show_urls: footnote

execute:
  execute_notebooks: 'off'
  stderr_output: show
  timeout: 300

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
    - deflist

html:
  # announcement: '<p>💃 Fandango is currently in development - see our <a href="https://github.com/fandango-fuzzer/fandango/issues"  style="color:white;">list of bugs and incomplete features</a>. A first beta release is scheduled for early April 2025.</p>'
  use_issues_button: true
  use_repository_button: true

repository:
  url: "https://github.com/uds-se/fuzzingbook/"

launch_buttons:
  binderhub_url: "https://mybinder.org/v2/gh/uds-se/fuzzingbook/HEAD?labpath=docs%2Fnotebooks/index.ipynb"
  thebe: true
